import type { Metadata } from "next";
import {
  Figtree,
  Kalam,
  Shadows_Into_Light_Two,
  Work_Sans,
  Albert_Sans,
  Inter,
} from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});
const kalam = Kalam({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kalam",
});
const shadowIntoLightTwo = Shadows_Into_Light_Two({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-shadow-into-light-two",
});

const figTree = Figtree({ subsets: ["latin"], variable: "--font-figtree" });
const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          inter.variable,
          albertSans.variable,
          kalam.variable,
          shadowIntoLightTwo.variable,
          workSans.variable,
          figTree.variable,
          "font-handwriting"
        )}
      >
        {children}
      </body>
    </html>
  );
}
