import type { Metadata } from "next";
import { Kalam, Shadows_Into_Light_Two } from "next/font/google";
import "./globals.css";

const kalam = Kalam({ subsets: ["latin"], weight: ["300", "400", "700"] });
const shadowIntoLightTwo = Shadows_Into_Light_Two({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kalam.className} ${shadowIntoLightTwo.className}`}>
        {children}
      </body>
    </html>
  );
}
